[package]
name = "cozal"
version = "0.1.0"
authors = ["Mason Boeman <masonboeman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.2"
tokio = { version = "0.2", features = ["full"] }
deno_core = "0.32.0"
