[package]
name = "cozal"
version = "0.0.1"
authors = ["Mason Boeman <masonboeman@gmail.com>"]
edition = "2018"
repository = "https://github.com/maboesanman/cozal.git"
description = "deterministic game event pipeline with isolated configurable components"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.40"
lazy_static = "1.4.0"
pin-project = "0.4.23"
futures = "0.3.5"
im = "15.0.0"

tokio = { path = "../Forks/tokio/tokio", features = ["time", "rt-threaded", "macros", "blocking"] }
winit = "0.22.2"
flume = "0.7.2"