[package]
name = "cozal"
version = "0.1.0"
authors = ["Mason Boeman <masonboeman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.21", features = ["time", "rt-threaded", "macros"] }
flume = "0.7.1"
lazy_static = "1.4.0"
im = "15.0.0"
winit = "0.22.2"
# deno_core = "0.32.0"