name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2


    - name: Install nightly
      run: rustup toolchain install nightly
    - name: Build
      run: rustup run nightly cargo build --verbose
    - name: install tarupaulin
      run: rustup run nightly cargo install cargo-tarpaulin
    - name: Run tests + coverage
      run: rustup run nightly cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error:     true