name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Install llvm tools
      run: rustup component add llvm-tools-preview
      shell: bash

    - name: Install grcov
      run: cargo install grcov
      shell: bash

    - name: Build, Instrument, Test
      env:
        LLVM_PROFILE_FILE: target/debug/coverage/%p-%m.profraw
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: -Zinstrument-coverage -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
        RUSTDOCFLAGS: -Cpanic=abort
        COVERALLS_TOKEN: ${{ secrets.coveralls_token }}
      run: ./calculate-coverage.sh

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.codecov_token }}
        file: codecov.json
        flags: Test
        name: Cargo Tests
        fail_ci_if_error: true
