name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      run: rustup toolchain install stable
    - name: Build
      run: rustup run stable cargo build --verbose
    - name: Run tests
      run: rustup run stable cargo test --verbose
